In [1]:
import numpy as np
import tensorflow as tf

In [2]:
aIn = np.array([1.,2.,3.,4.,5.])

#Vector Implementation

In [3]:
def CustomSoftmax(a):
  e = np.exp(a)
  return e/np.sum(e)

# Non-Vector Implementation

In [4]:
def CustomSoftmax2(aIn):
  counts = len(aIn)
  ez = 0
  aOut = np.zeros(counts)
  for i in range(counts):
    ez += np.exp(aIn[i])
  for i in range(counts):
    aOut[i] = np.exp(aIn[i])/ez

  return aOut


In [5]:
reply1 = tf.nn.softmax(aIn)
reply2 = CustomSoftmax(aIn)
reply3 = CustomSoftmax2(aIn)
print(reply1)
print(reply2)
print(reply3)

tf.Tensor([0.01165623 0.03168492 0.08612854 0.23412166 0.63640865], shape=(5,), dtype=float64)
[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
[0.01165623 0.03168492 0.08612854 0.23412166 0.63640865]
