In [8]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import matplotlib.pyplot as plt

In [9]:
x = np.load('/content/data/X.npy')
y = np.load('/content/data/y.npy')

#Sequential dense layers implementation in tensorflow directly

In [10]:
model = Sequential(                      
    [                                   
        tf.keras.Input(shape=(400,)), 
        Dense(25, activation='sigmoid'), 
        Dense(15, activation='sigmoid'), 
        Dense(1,  activation='sigmoid')  
    ], name = "modelname"                                    
)

In [11]:
model.compile(
    loss=tf.keras.losses.BinaryCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001),
)

model.fit(
    x,y,
    epochs=20
)

Epoch 1/20
157/157 [==============================] - 1s 2ms/step - loss: -7.9560
Epoch 2/20
157/157 [==============================] - 0s 2ms/step - loss: -16.6482
Epoch 3/20
157/157 [==============================] - 0s 2ms/step - loss: -22.3070
Epoch 4/20
157/157 [==============================] - 0s 2ms/step - loss: -27.5543
Epoch 5/20
157/157 [==============================] - 0s 2ms/step - loss: -32.6611
Epoch 6/20
157/157 [==============================] - 0s 2ms/step - loss: -37.6944
Epoch 7/20
157/157 [==============================] - 0s 2ms/step - loss: -42.6889
Epoch 8/20
157/157 [==============================] - 0s 2ms/step - loss: -47.6700
Epoch 9/20
157/157 [==============================] - 0s 2ms/step - loss: -52.6325
Epoch 10/20
157/157 [==============================] - 0s 2ms/step - loss: -57.5670
Epoch 11/20
157/157 [==============================] - 0s 2ms/step - loss: -63.0854
Epoch 12/20
157/157 [==============================] - 0s 2ms/step - loss: -70.0988
Ep

In [13]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 25)                10025     
                                                                 
 dense_4 (Dense)             (None, 15)                390       
                                                                 
 dense_5 (Dense)             (None, 1)                 16        
                                                                 
Total params: 10,431
Trainable params: 10,431
Non-trainable params: 0
_________________________________________________________________


In [52]:
[layer1, layer2, layer3] = model.layers

In [55]:
layer1.get_weights()

[array([[-0.02307746,  0.09349397, -0.02975717, ...,  0.05268727,
          0.0357565 , -0.09891094],
        [ 0.02682284, -0.09862656, -0.09163042, ...,  0.06456226,
          0.0024261 , -0.02592848],
        [ 0.00890265, -0.08471087, -0.02355483, ...,  0.02012274,
          0.11871052, -0.07019313],
        ...,
        [ 0.0241057 ,  0.03376791, -0.02196025, ..., -0.02235419,
          0.05822559,  0.05391603],
        [-0.01662107, -0.08254587,  0.04368133, ...,  0.03231416,
         -0.10030812, -0.02279266],
        [ 0.05956219, -0.09739895,  0.07974939, ...,  0.10059433,
          0.04115041, -0.10999062]], dtype=float32),
 array([ 0.14032532,  0.15417641,  0.13427396,  0.18726967,  0.1937438 ,
         0.11001679,  0.15323888,  0.18303466,  0.12595916, -0.06708688,
         0.14508663,  0.18649544,  0.13127835,  0.18588774,  0.15503158,
         0.13918824,  0.15421858,  0.17957056,  0.1571267 ,  0.16963334,
         0.14002457,  0.1487611 ,  0.18454918,  0.16318163,  0.171

#Individual Dense Layer operation

In [58]:
def IndividualDense(a_in, W, b, g):

    iterations = W.shape[1]
    a_out = np.zeros(iterations)

    for each in range(iterations):
      w = W[:,each]
      z = np.dot(w,a_in) + b[each]
      a_out[each] = g(z)
    
    return a_out

In [35]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [67]:
xTest = np.arange(1,3,1).reshape(2,)
WTest = np.arange(1,7,1).reshape(2,3)
bTest = np.arange(1,4,1).reshape(3,)
aTest = IndividualDense(xTest, WTest, bTest, sigmoid)
print(aTest)

[0.9999546  0.99999917 0.99999998]


array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6]])

In [59]:
def CustomSequential(X,w1,b1,w2,b2,w3,b3):
  a1 = IndividualDense(X,w1,b1,sigmoid)
  a2 = IndividualDense(a1,w2,b2,sigmoid)
  a3 = IndividualDense(a2,w3,b3,sigmoid)
  return a3

Using weights from pretrained models for making custom sequential

In [60]:
w1,b1 = layer1.get_weights()
w2,b2 = layer2.get_weights()
w3,b3 = layer3.get_weights()

In [65]:
w1.shape

(400, 25)

In [66]:
CustomSequential(x[0],w1,b1,w2,b2,w3,b3)

array([1.])